services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local
  
#---
#version: '3.3' #? right version

#services:
#  db:
#   image: mysql:8.2
#   restart: always
#   environment:
#    MYSQL_DATABASE: 'db'
#   # So you dont have to use root
#    MYSQL_USER: 'user'
#    MYSQL_PASSWORD: 'password'
#    MYSQL_ROOT_PASSWORD: 'password'
#   ports:
#    - '3306:3306'
#   expose:
#    - '3306'
#   volumes:
#    - my-db:/var/lib/mysql
#  mail-dev: # It is an image to create a mailserver for development
#   container_name: mail-dev-bsn
#   image: maildev/maildev
#   ports:
#    - 1080/1080
#    - 1025/1025
#    
#volumes:
#  my-db:
  
