spring:
 datasource:
  url: jdbc:postgresql://localhost:5432/book_rental_network
  username: username
  password: password
  driver-class-name: org.postgresql.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: false
  properties:
   hibernate:
    format_sql:
  database: postgresql
  database-platform: org.hibernate.dialect.PostgreSQLDialect
 mail:
  host: localhost
  port: 1025
  username: tharoxes
  password: tharoxes
  properties:
   mail:
    smtp:
     trust: "*"
    auth: true
    starttls:
     enable: true
    connectiontimeout: 5000
    timeout: 3000
    writetimeout: 5000
    
 application:
  security:
   jwt:
    secret-key: 45F4ASDF6A5FD46SDDAF46D54S65AF46
    expiration: 8640000
  mailing:
   frontend:
    activation-url: http://localhost:4200/activate_account
server:
 port: 8088