spring:
 profiles:
  active: dev
 servlet:
  multipart:
   max-file-size: 50MB
springdoc:
 default-produces-media-type: application/json

server:
 servlet:
  context-path: /api/v1/
  
 # --------------------------------------------------

spring:
 datasource:
  url: jdbc:mysql://localhost:3306/book_rental_network
  username: springstudent
  password: springstudent
  driver-class-name: org.mysql.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: false
  properties:
   hibernate:
    format_sql:
  database: mysql
  database-platform: org.hibernate.dialect.Mysql
 mail:
  host: localhost
  port: 1025
  username: tharoxes
  password: tharoxes
  properties:
   mail:
    smtp:
     trust: "*"
    auth: true
    starttls:
     enable: true
    connectiontimeout: 5000
    timeout: 3000
    writetimeout: 5000
    
 application:
  security:
   jwt:
    secret-key: 45F4ASDF6A5FD46SDDAF46D54S65AF46
    expiration: 6969123